In [19]:
from tensorflow.keras.models import load_model
import pickle
import numpy as np
import pandas as pd

In [20]:
model = load_model('Ann_model.h5')

In [21]:
with open('gender_label_encoder.pkl','rb') as f:
    gender_label = pickle.load(f)
    
with open('geo_onehot_encoder.pkl','rb') as f:
    geo_onehot_encoder = pickle.load(f)
    
with open('scaler.pkl','rb') as f:
    scaler = pickle.load(f)

In [22]:
gender_label.classes_[0]

'Female'

In [23]:
input_data={
    'CreditScore':619,
    "Geography":"France",
    "Gender":'Female',
    "Age":42,
    'Tenure':2,
    'Balance':0.00,
    'NumOfProducts':1,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':101348
}

In [24]:
input_data

{'CreditScore': 619,
 'Geography': 'France',
 'Gender': 'Female',
 'Age': 42,
 'Tenure': 2,
 'Balance': 0.0,
 'NumOfProducts': 1,
 'HasCrCard': 1,
 'IsActiveMember': 1,
 'EstimatedSalary': 101348}

In [25]:
geo_encoded = geo_onehot_encoder.transform([[input_data['Geography']]])

C:\Users\Anmino\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  


In [26]:
geo_encoded

array([[1., 0., 0.]])

In [20]:
geo_encoded_df = pd.DataFrame(geo_encoded,columns=geo_onehot_encoder.get_feature_names_out(['Geography']))

In [21]:
geo_encoded_df

Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [25]:
input_df = pd.DataFrame([input_data])
input_df

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France  Female   42       2      0.0              1          1               1           101348

In [26]:
input_df['Gender'] = gender_label.transform(input_df['Gender'])

In [27]:
input_df

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary
0          619    France       0   42       2      0.0              1          1               1           101348

In [31]:
final_data = pd.concat([input_df.drop('Geography',axis=1),geo_encoded_df],axis=1)
final_data

CreditScore  Gender  Age  Tenure  ...  EstimatedSalary  Geography_France  Geography_Germany  Geography_Spain
0          619       0   42       2  ...           101348               1.0                0.0              0.0

[1 rows x 12 columns]

In [32]:
input_scales = scaler.transform(final_data)
input_scales

array([[-0.33880827, -1.09499335,  0.29493847, -1.04241787, -1.21847056,
        -0.91668767,  0.64920267,  0.97481699,  0.01593854,  1.00150113,
        -0.57946723, -0.57638802]])

In [34]:
prediction = model.predict(input_scales)
prediction

1/1 [==============================] - 0s 19ms/step


array([[0.3768247]], dtype=float32)

In [36]:
prediction_problity = prediction[0][0]
prediction_problity

0.3768247

In [37]:
if prediction_problity > 0.5:
    print("The customer is likely  to churn")
    
else:
    print("The customer is not likely to churn")

The customer is not likely to churn
